os: linux
dist: bionic
language: php

services: mysql

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

env:
  - WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test DB_USER=root DB_PASSWORD='' DB_NAME=test

jobs:
  allow_failures:
    - php: 8.0
    - php: nightly

before_script:
  # Downgrade Composer to latest 1.x series
  - composer self-update 1.10.16
  # Install composer packages before trying to activate themes or plugins
  - composer install
  # Create database
  - mysqladmin create $DB_NAME --user="$DB_USER" --password="$DB_PASSWORD"
  # Install router so that we don't need nginx/php-fpm
  - curl -s https://raw.githubusercontent.com/Seravo/wordpress-test-template/master/lib/router.php > htdocs/router.php
  # Start php server on background
  - cd htdocs && php -S 0.0.0.0:12000 router.php &
  # Install WordPress with wp-cli
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - php wp-cli.phar core install --url=$WP_TEST_URL --title='Test' --admin_user=$WP_TEST_USER --admin_password=$WP_TEST_USER_PASS --admin_email="$WP_TEST_USER@wordpress.dev" --path=htdocs/wordpress

  # Activate all plugins
  - php wp-cli.phar plugin activate --all --path=htdocs/wordpress

  # test webserver
  - curl -i http://localhost:12000

  # Install packages for gulp
  - npm install

  # Test gulp and compile assets
  - ./node_modules/.bin/gulp

script:
  # Remove one file to avoid false positive __autoload() detection by php -l later on
  - rm htdocs/wordpress/wp-includes/spl-autoload-compat.php
  # Syntax check all php files and fail for any error text in STDERR
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
  # @TODO: Run a more extensive test using the above real WordPress installation
