name: Acceptance tests

on: [pull_request]

env:
  CONTAINER: wordpress
  CI_IMAGE: docker.io/seravo/wordpress:ci

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Codeception acceptance tests
        run: |
          docker run --name "${{env.CONTAINER}}" \
            --hostname "${{env.CONTAINER}}" \
            --volume "/tmp/data/:/data" \
            --volume "$(pwd):/data/wordpress" \
            --env WP_USER_UID=1001 \
            --env DEBUG=true \
            --env WP_USER_PASS="${{github.sha}}" \
            --rm "${{env.CI_IMAGE}}"
